"""initial

Revision ID: 2158bad7724c
Revises:
Create Date: 2026-02-10 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '2158bad7724c'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('movies', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_movies_title'), 'movies', ['title'], unique=False)
    op.create_unique_constraint(None, 'directors', ['name'])
    op.create_unique_constraint(None, 'genres', ['name'])
    # ### end Alembic commands ###

    # Manually added: Set default timestamps for existing rows
    op.execute("UPDATE movies SET created_at = NOW() AT TIME ZONE 'utc', updated_at = NOW() AT TIME ZONE 'utc'")

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'genres', type_='unique')
    op.drop_constraint(None, 'directors', type_='unique')
    op.drop_index(op.f('ix_movies_title'), table_name='movies')
    op.drop_column('movies', 'updated_at')
    op.drop_column('movies', 'created_at')
    # ### end Alembic commands ###